version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: invest_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d invest_bot"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD: "True"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./init-pgadmin.py:/init-pgadmin.py
    command: sh -c "python3 /init-pgadmin.py & /entrypoint.sh"

  bot:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: postgresql://admin:123456@postgres:5432/invest_bot
      NODE_ENV: development
      CHANNEL_ID: ${CHANNEL_ID}
      ADMIN_ID: ${ADMIN_ID}
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
